SET ECHO ON VERIFY OFF FEEDBACK ON


PROMPT === Creating schema objects ===
PROMPT === MOVIES (CATALOG) ===

CREATE TABLE Movies (
    ID  VARCHAR2(10) PRIMARY KEY,
    Movie_Name   VARCHAR2(50) NOT NULL,
    Price   DECIMAL(6,2) DEFAULT 0 CHECK (Price >= 0),
    Genre   VARCHAR2(25),
    Copies  NUMBER(3) DEFAULT 0 CHECK (Copies >=0),
    Avg_Rating  DECIMAL(3,1) CHECK (Avg_Rating BETWEEN 0 AND 5),
    Release_Date    DATE,
    Runtime_Min NUMBER(4) CHECK (Runtime_Min > 0),
    Age_Rating  VARCHAR2(10),
    Language_Code   VARCHAR2(5)
);

PROMPT === CUSTOMER ===
CREATE TABLE Customer (
    Username    VARCHAR2(10) PRIMARY KEY,
    Balance DECIMAL(10,2) DEFAULT 0 CHECK (Balance >=0),
    Password    VARCHAR2(25) NOT NULL,
    First_Name  VARCHAR2(50),
    Last_Name   VARCHAR2(50),
    Age NUMBER(3) CHECK (Age BETWEEN 12 AND 110),
    Email   VARCHAR2(50),
    Phone VARCHAR2(25)
);

PROMPT === INVENTORY (parent for library) ===
CREATE TABLE Inventory (
    Copy_ID VARCHAR2(12) PRIMARY KEY,
    Movie_ID    VARCHAR2(10) NOT NULL,
    Quality VARCHAR2(12) DEFAULT '1080P' NOT NULL CHECK (Quality in ('4K', '1080P', '720P', '480P')),
    Status  VARCHAR2(12) DEFAULT 'AVAILABLE' NOT NULL CHECK (Status in ('AVAILABLE', 'RENTED','RESERVED')),
    FOREIGN KEY (Movie_ID) REFERENCES Movies(ID)
);

PROMPT === Library (rented) ===
CREATE TABLE Library (
    Username    VARCHAR2(10) NOT NULL,
    Movie_ID    VARCHAR2(10) NOT NULL,
    Copy_ID VARCHAR2(12) NOT NULL,
    Start_Date  DATE DEFAULT TRUNC(SYSDATE) NOT NULL,
    Due_Date    DATE GENERATED ALWAYS AS (Start_Date + 7) VIRTUAL,
    Returned_On DATE,
    PRIMARY KEY (Copy_ID, Start_Date),
    FOREIGN KEY (Username) REFERENCES Customer(Username),
    FOREIGN KEY (Movie_ID) REFERENCES Movies(ID),
    FOREIGN KEY (Copy_ID) REFERENCES Inventory(Copy_ID),
    CHECK (Returned_On IS NULL OR Returned_On >= Start_Date)
);


PROMPT === Review ===
CREATE TABLE Review (
    Review_ID   NUMBER(12) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Username VARCHAR2(10) NOT NULL,
    Movie_ID    VARCHAR2(10) NOT NULL,
    Rating  NUMBER(1) NOT NULL CHECK (Rating BETWEEN 1 AND 5),
    Review_text VARCHAR2(50),
    Created_At  DATE DEFAULT SYSDATE NOT NULL,
    FOREIGN KEY (Username) REFERENCES Customer(Username),
    FOREIGN KEY (Movie_ID) REFERENCES Movies(ID),
    UNIQUE (Username, Movie_ID)
);

PROMPT === CUSTOMER SERVICE ===
CREATE TABLE Customer_Service (
    Employee_ID VARCHAR2(10) PRIMARY KEY,
    SHIFT   VARCHAR2(10),
    Password    VARCHAR2(25) NOT NULL,
    EMAIL   VARCHAR2(50)
);

PROMPT === CONTENT MANAGER ===
CREATE TABLE Content_Manager (
    Employee_ID VARCHAR2(10) PRIMARY KEY,
    Movie_To_Change VARCHAR2(10),
    Password    VARCHAR2(25) NOT NULL,
    EMAIL   VARCHAR2(50)
);

PROMPT === DEVELOPER ===
CREATE TABLE Developer (
    Employee_ID VARCHAR2(10) PRIMARY KEY,
    Email   VARCHAR2(50) NOT NULL,
    Password    VARCHAR(72) NOT NULL,
    Specialty   VARCHAR2(50) DEFAULT 'BACKEND' NOT NULL CHECK (Specialty in ('BACKEND', 'FRONTEND')), 
    GitHub  VARCHAR2(80)
);


COMMIT;
EXIT;