SET ECHO ON VERIFY OFF FEEDBACK ON

PROMPT === Creating schema objects for A8 ===

------------------------------------------------------------
-- MOVIE INFORMATION & COPIES
------------------------------------------------------------
PROMPT === MOVIE_INFORMATION ===
CREATE TABLE Movie_information (
    Movie_ID        VARCHAR2(10) PRIMARY KEY,
    Movie_Name      VARCHAR2(50) NOT NULL,
    Price           DECIMAL(6,2) DEFAULT 0 CHECK (Price >= 0),
    Genre           VARCHAR2(25),
    Copies          NUMBER(3) DEFAULT 0 CHECK (Copies >= 0),
    Avg_Rating      DECIMAL(3,1) CHECK (Avg_Rating BETWEEN 0 AND 5),
    Release_Date    DATE,
    Runtime_Min     NUMBER(4) CHECK (Runtime_Min > 0),
    Age_Rating      VARCHAR2(10),
    Language_Code   VARCHAR2(5)
);

PROMPT === MOVIE_COPY ===
CREATE TABLE Movie_copy (
    Copy_ID     VARCHAR2(12) PRIMARY KEY,
    Movie_ID    VARCHAR2(10) NOT NULL,
    FOREIGN KEY (Movie_ID) REFERENCES Movie_information(Movie_ID)
);

------------------------------------------------------------
-- CUSTOMER TABLES (SECURITY + PUBLIC INFO)
------------------------------------------------------------
PROMPT === CUSTOMER_SECURITY_INFO ===
CREATE TABLE Customer_security_info (
    Username    VARCHAR2(10) PRIMARY KEY,
    Balance     DECIMAL(10,2) DEFAULT 0 CHECK (Balance >= 0),
    Password    VARCHAR2(25) NOT NULL,
    First_Name  VARCHAR2(50),
    Last_Name   VARCHAR2(50)
);

PROMPT === CUSTOMER_PUBLIC_INFO ===
CREATE TABLE Customer_public_info (
    Email       VARCHAR2(50) PRIMARY KEY,
    First_Name  VARCHAR2(50),
    Last_Name   VARCHAR2(50),
    Age         NUMBER(3) CHECK (Age BETWEEN 12 AND 110),
    Phone       VARCHAR2(25)
    -- Optional: if you decide to link these using (First_Name, Last_Name),
    -- you would add a foreign key, but A8 does not explicitly require it.
);

------------------------------------------------------------
-- BORROW / LIBRARY (RENTS)
------------------------------------------------------------
PROMPT === BORROW ===
CREATE TABLE Borrow (
    Copy_ID     VARCHAR2(12) NOT NULL,
    Username    VARCHAR2(10) NOT NULL,
    Start_Date  DATE DEFAULT TRUNC(SYSDATE) NOT NULL,
    Due_Date    DATE GENERATED ALWAYS AS (Start_Date + 7) VIRTUAL,
    Returned_On DATE,
    PRIMARY KEY (Copy_ID, Username, Start_Date),
    FOREIGN KEY (Copy_ID) REFERENCES Movie_copy(Copy_ID),
    FOREIGN KEY (Username) REFERENCES Customer_security_info(Username),
    CHECK (Returned_On IS NULL OR Returned_On >= Start_Date)
);

------------------------------------------------------------
-- REVIEWS
------------------------------------------------------------
PROMPT === COMPACT_REVIEW ===
CREATE TABLE Compact_Review (
    Review_ID   NUMBER(12) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Username    VARCHAR2(10) NOT NULL,
    Movie_ID    VARCHAR2(10) NOT NULL,
    Rating      NUMBER(1) NOT NULL CHECK (Rating BETWEEN 1 AND 5),
    Review_Text VARCHAR2(50),
    Created_At  DATE DEFAULT SYSDATE NOT NULL,
    FOREIGN KEY (Username) REFERENCES Customer_security_info(Username),
    FOREIGN KEY (Movie_ID) REFERENCES Movie_information(Movie_ID),
    UNIQUE (Username, Movie_ID)
);

------------------------------------------------------------
-- INVENTORY DETAILS PER COPY
------------------------------------------------------------
PROMPT === INVENTORY_COPY_DETAIL ===
CREATE TABLE Inventory_Copy_Detail (
    Copy_ID VARCHAR2(12) PRIMARY KEY,
    Quality VARCHAR2(12) DEFAULT '1080P' NOT NULL
        CHECK (Quality IN ('4K', '1080P', '720P', '480P')),
    Status  VARCHAR2(12) DEFAULT 'AVAILABLE' NOT NULL
        CHECK (Status IN ('AVAILABLE', 'RENTED', 'RESERVED')),
    FOREIGN KEY (Copy_ID) REFERENCES Movie_copy(Copy_ID)
);

------------------------------------------------------------
-- CUSTOMER SERVICE STAFF
------------------------------------------------------------
PROMPT === EMPLOYEE_INFO_CUSTOMER_SERVICE ===
CREATE TABLE Employee_info_customer_service (
    Employee_ID VARCHAR2(10) PRIMARY KEY,
    Email       VARCHAR2(50) UNIQUE,
    Password    VARCHAR2(25) NOT NULL
);

PROMPT === SHIFT_INFO_CUSTOMER_SERVICE ===
CREATE TABLE Shift_info_customer_service (
    Email   VARCHAR2(50) PRIMARY KEY,
    Shift   VARCHAR2(10),
    FOREIGN KEY (Email) REFERENCES Employee_info_customer_service(Email)
);

------------------------------------------------------------
-- CONTENT MANAGER STAFF
------------------------------------------------------------
PROMPT === EMPLOYEE_INFO_CM ===
CREATE TABLE Employee_info_CM (
    Employee_ID VARCHAR2(10) PRIMARY KEY,
    Email       VARCHAR2(50) UNIQUE,
    Password    VARCHAR2(25) NOT NULL
);

PROMPT === CM_MOVIE_TO_CHANGE ===
CREATE TABLE CM_movie_to_change (
    Email           VARCHAR2(50) PRIMARY KEY,
    Movie_to_change VARCHAR2(10),
    FOREIGN KEY (Email) REFERENCES Employee_info_CM(Email),
    FOREIGN KEY (Movie_to_change) REFERENCES Movie_information(Movie_ID)
);

------------------------------------------------------------
-- DEVELOPERS
------------------------------------------------------------
PROMPT === DEVELOPER_MAIN ===
CREATE TABLE Developer_main (
    Employee_ID VARCHAR2(10) PRIMARY KEY,
    Github      VARCHAR2(80),
    Email       VARCHAR2(50) NOT NULL,
    Password    VARCHAR2(72) NOT NULL
);

PROMPT === DEVELOPER_SPECIALITY ===
CREATE TABLE Developer_speciality (
    Email       VARCHAR2(50) NOT NULL,
    Github      VARCHAR2(80) NOT NULL,
    Specialty   VARCHAR2(50) DEFAULT 'BACKEND' NOT NULL
        CHECK (Specialty IN ('BACKEND', 'FRONTEND')),
    PRIMARY KEY (Email, Github),
    FOREIGN KEY (Email, Github)
        REFERENCES Developer_main(Email, Github)
);

COMMIT;
EXIT;
